FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm ci
RUN npm i typescript

COPY . .

RUN npm run build

RUN npm cache clean --force

FROM node:18-alpine as production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package*.json ./

CMD ["node", "dist/Worker.js"]
